### ISSUE TITLE
How to make an event or make a loop

### ISSUE THREAD

**Issue by wasimjee** [vik-borisov/TelegramClient#21]
how to make an event or loop so that client gets the update if a new message is received.

**Comment by vik-borisov** [comment]
Look at the quick start:
Https://github.com/vik-borisov/TelegramClient/wiki/Quick-Start#to-receive-updates-you-must-subscribe-to-the-event

**Comment by vik-borisov** [comment]
I was found some bugs and fixes it

**Comment by vik-borisov** [comment]
please, rechecking a update event
