### ISSUE TITLE
Can't connect to production server

### ISSUE THREAD

**Issue by TFTomSun** [vik-borisov/TelegramClient#27]
Hi,
when i use your API, connection to the test server works, but when i try to connect to the production server the ConnectAsync method never returns. Do you have the same issue?

Btw. these are the servers i got via the telegram website... but i assume that they are the same for everyone:
 var testServerAddress = "149.154.167.40";
var productionServerAddress = "149.154.167.50";

**Comment by vik-borisov** [comment]
Hi, 
please, write your code

**Comment by TFTomSun** [comment]
var genericAppId = ...;
                    var genericApiHash =...;
                    var testServerAddress = "149.154.167.40";
                    var productionServerAddress = "149.154.167.50";
                    var serverAddress = productionServerAddress;
                    var port = 443;
                    var client = ClientFactory.BuildClient(genericAppId, genericApiHash, serverAddress, port);
                    await client.ConnectAsync(); // works when serverAddress = testServerAddress, hangs when serverAddress = productionServerAddress

**Comment by vik-borisov** [comment]
Please delete the folder bin and try again.
TelegramClient is  remember your session in the session.dat file

**Comment by TFTomSun** [comment]
had to delete the session.dat file which is created in the project folder. Please consider to let the user decide how (database, file, serialization format) and where (file location) he stores the data. Simply add some Action parameter that let the user store the credentials. It's also not the best idea to write something in the bin folder, because the end user might not have write access to that folder.

**Comment by vik-borisov** [comment]
@TFTomSun Ok, i'm created the issue #28
