### ISSUE TITLE
help

### ISSUE THREAD

**Issue by a-rahmani1998** [vik-borisov/TelegramClient#34]
Hi , I use this library 👍  but I receive error / for example > error for send code to phone number :
![68](https://user-images.githubusercontent.com/31850943/30273898-e0a3a664-96af-11e7-9ad8-0e5525411ef9.PNG)
my project:
`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TelegramClient.Core;

namespace sinister_v6
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        ITelegramClient client;
        string hash;
        private async void Form1_Load(object sender, EventArgs e)
        {
            try
            {
                client = ClientFactory.BuildClient(123205, "202725e8a82ac37ecd248eef4cbxxxxx", "149.154.175.xxx", 443);
                await client.ConnectService.ConnectAsync();
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private async void btnPhone_Click(object sender, EventArgs e)
        {
            try { 
var hash = await client.AuthService.SendCodeRequestAsync(txtPhone.Text);
        }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
       
        private async void btnCode_Click(object sender, EventArgs e)
        {
                var user = await client.AuthService.MakeAuthAsync(txtPhone.Text, hash, txtCode.Text);
       
            }
        }

    }`
pls upload sample source code
thanks

**Comment by vik-borisov** [comment]
hi, @a-rahmani1998 
What is the IP address of the server?

**Comment by a-rahmani1998** [comment]
@vik-borisov 
![69](https://user-images.githubusercontent.com/31850943/30275503-65f60842-96b6-11e7-898a-e4e50a7d186f.PNG) is true?

**Comment by a-rahmani1998** [comment]
pls answer my question in above
other question >>
my code in above is true? else package or reference add to my project? see this pic >>
1)
![72](https://user-images.githubusercontent.com/31850943/30296289-84eb8c08-96f8-11e7-9d7a-9a41faa50061.PNG)
2)
![71](https://user-images.githubusercontent.com/31850943/30296290-84ed1730-96f8-11e7-9329-78de078d645d.PNG)

pls help me
tnx

**Comment by vik-borisov** [comment]
@a-rahmani1998 

I have corrected a [quick start](../wiki/Quick-Start) guide to version 0.3.x. This will fix some of the errors

**Comment by vik-borisov** [comment]
@ a-rahmani1998, please use the production configuration, since the test configuration is an isolated system and you need to create a new user for this configuration

**Comment by vik-borisov** [comment]
Also look at the [tests](https://github.com/vik-borisov/TelegramClient/blob/master/tests/TelegramClient.Tests/TelegramClientTests.cs). They work

**Comment by a-rahmani1998** [comment]
@vik-borisov 
Thanks and wish you were successful / if a person uploaded the source code / was awesome

**Comment by vik-borisov** [comment]
@a-rahmani1998, Do you have any problems?

**Comment by a-rahmani1998** [comment]
@vik-borisov - hi, I used [test](https://github.com/vik-borisov/TelegramClient/blob/master/tests/TelegramClient.Tests/TelegramClientTests.cs) for solve error(phone-migrate) in my project But the errors did not resolve .for example my code ;
![79](https://user-images.githubusercontent.com/31850943/30535164-2c97ab4a-9c16-11e7-89ab-ce1465bfda3b.PNG)

/// 
error:
![78](https://user-images.githubusercontent.com/31850943/30535184-4382f6de-9c16-11e7-81bc-9e77d34243f4.PNG)



pls , help me for create my app
,

**Comment by a-rahmani1998** [comment]
@vik-borisov , await For Answer ♥

**Comment by vik-borisov** [comment]
hi, @a-rahmani1998 
Do you need help?
