### ISSUE TITLE
Channel

### ISSUE THREAD

**Issue by armin-mohammadi-codes** [vik-borisov/TelegramClient#36]
hello ,
    how to join channel with link ?

**Comment by vik-borisov** [comment]
Hello, @arminblack !
Please, look at https://github.com/wfjsw/telegram-core-docs/blob/master/method/messages.checkChatInvite.md

**Comment by OleksiyMoroz** [comment]
Hello! I have this error while try to Connect client: 
"The value '47' of 'sharedKey' is not expected. Expected value is '256.'"
Can you help?
