### ISSUE TITLE
Connect Issue

### ISSUE THREAD

**Issue by OleksiyMoroz** [vik-borisov/TelegramClient#37]
Hello! I have this error while trying to Connect client:
"The value '47' of 'sharedKey' is not expected. Expected value is '256.'"
Can you help?

**Comment by OleksiyMoroz** [comment]
Fixed! Helped run client.ReAuth
Can you answer this questions?
1. There a way to store separated "session" file for each client of the App?
2. In sources, i sow that you use APIVersion = 1.0m is this mean MTProto v.1.0? Do you plan to migrate to MTProto v.2.0?
Thanks! Awesome work with this client! 
3. Any way to Dispose Client?

**Comment by vik-borisov** [comment]
Hello, @OleksiyMoroz 
1. use different sessionUserId parameters for each instance
![image](https://user-images.githubusercontent.com/4207463/33836784-0006598e-debd-11e7-85e1-226879d7d2c6.png)

2. #38

3. #39
