### ISSUE TITLE
Get an exception 'API_ID_INVALID'

### ISSUE THREAD

**Issue by altafard** [vik-borisov/TelegramClient#4]
When i try get sms code by calling method `SendCodeRequestAsync` i have got an exception 'API_ID_INVALID'.

**Comment by vik-borisov** [comment]
Hi, @Altafard!
Which Telegram's server do you connect to?

**Comment by altafard** [comment]
I tried to connect both server (test 149.154.167.40:443 and prod 149.154.167.50:443). Result same

**Comment by vik-borisov** [comment]
@Altafard,
Test server have own infrastructure. Can you send me your API_ID?

**Comment by altafard** [comment]
Sure, my api_id is 108897

**Comment by vik-borisov** [comment]
@Altafard,  please, send me your api_hash on my public email. I will try reproduce your problem

**Comment by vik-borisov** [comment]
The question resolved itself
