### ISSUE TITLE
ReAuth with Update events

### ISSUE THREAD

**Issue by OleksiyMoroz** [vik-borisov/TelegramClient#43]
Hello!
When client is created, I call "ConnectAsync" and "MakeAuthAsync" with code
then I can subscribe to Update events and this works
BUT 
If I restart the app, try to build client via session.dat, connect, client already registered, 
subscribe to Updates and no update are figured, event don't trigger 
Can you help with this? 
Maybe I missed some function to call?

**Comment by vik-borisov** [comment]
Hello, @OleksiyMoroz !
Can you send me an example application with an error?

**Comment by OleksiyMoroz** [comment]
Hi! @vik-borisov !
![image](https://user-images.githubusercontent.com/20989635/34814152-456a69a6-f6b5-11e7-9c7c-4f7413697323.png)
![image](https://user-images.githubusercontent.com/20989635/34814438-4e21d880-f6b6-11e7-8bb2-d2dff8355d28.png)

on this images:
 1. Build client
 2. For the first log in user have to submit code(IsUserAuth = false) 
 3.  Send Code to Telegram and 5. MakeAuthAsync with code and after this Update event trigger
 4. This part will work if session.dat exist and if so IsUserAuth = true, but in this case Update events will no trigger. 
Also, i tried to call ReAuth this time but function returns an error : "invalid checksum! skip"
What i'm doing wrong? There a way to reuse session.dat or i need always create new session and request the code? Thanks! 
Also HandlingUpdates functions 
![image](https://user-images.githubusercontent.com/20989635/34814702-4f321c98-f6b7-11e7-8c69-0837ce92235e.png)

**Comment by vik-borisov** [comment]
Hello, @OleksiyMoroz !
Can you send me an example application with an error?

**Comment by vik-borisov** [comment]
4 step is not needed. Because authentication occurs when the Connect method is called. Reconnect is needed to change the authentication key for an open connection.

**Comment by OleksiyMoroz** [comment]
@vik-borisov 
still, Updates event don't triggering if build client via session file
works if client newly created.
also few moments that I want to tell you:
 1. noticed that RconnectToDCAsync return error that tells WorkThread are busy
so for now solution to relogin or set new server afte PHONE_MIGRATE_X errors is creating new client with different session name, but it's not the best way
 2. as I see on telegram API docs, you no need to specify the server in auth function, it's optional, but in your method, it's required, can you also do this optional? Or implement "getUpdates" api function, so we can get the nearest server and use them? server that tell telegram when you create an app is wrong and return phone_migrate error
Thanks!

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
the session.dat file must be different for each user session.
If you have several users, then you need a separate client for each user with a separate session file.

**Comment by OleksiyMoroz** [comment]
@vik-borisov yes, yes
but one user, rerun app(on server) but session left for this client
auth via this session file will not handle updates

example: official telegram app, you can restart this, but no need to relogin, so app use same session for user

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
I just fixed the error handling USER_MIGRATE_X and PHONE_MIGRATE_X. Update the library to the latest version

**Comment by OleksiyMoroz** [comment]
@vik-borisov Ok, thank you! 
What do you do?
Also, can I work with several telegram users using one server?(same ip)

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
Yes, but you need different files to store sessions

**Comment by OleksiyMoroz** [comment]
@vik-borisov Ok, Thanks! 
So now i don't need logic for migrate errors, it's automated?

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
Yes, but please check. I'm not getting this error

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
please look at
https://github.com/vik-borisov/TelegramClient/blob/5ff6888fb95600b5501abf5d51030604b5aef35b/tests/TelegramClient.Tests/TelegramClientTests.cs#L241
https://github.com/vik-borisov/TelegramClient/blob/5ff6888fb95600b5501abf5d51030604b5aef35b/tests/TelegramClient.Tests/TelegramClientTests.cs#L261

This is a demonstration of working with updates

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
please look at
https://github.com/vik-borisov/TelegramClient/blob/5ff6888fb95600b5501abf5d51030604b5aef35b/tests/TelegramClient.Tests/TelegramClientTests.cs#L241
https://github.com/vik-borisov/TelegramClient/blob/5ff6888fb95600b5501abf5d51030604b5aef35b/tests/TelegramClient.Tests/TelegramClientTests.cs#L261

This is a demonstration of working with updates

**Comment by OleksiyMoroz** [comment]
@vik-borisov so calling for updates it's more stable than subscribe to the update event?

**Comment by OleksiyMoroz** [comment]
@vik-borisov and now i get error "invalid checksum! skip" then try to login

**Comment by OleksiyMoroz** [comment]
@vik-borisov do you have some list of number county codes and relayed telegram servers?

**Comment by vik-borisov** [comment]
> @vik-borisov so calling for updates it's more stable than subscribe to the update event?

This is another way to get updates.

>  and now i get error "invalid checksum! skip" then try to login

try to delete the session.dat file and try again.

**Comment by OleksiyMoroz** [comment]
Hello @vik-borisov !
about "invalid checksum! skip": 
removed session, still have this error
![image](https://user-images.githubusercontent.com/20989635/34867288-396fc014-f788-11e7-9353-95a14976c93e.png)

**Comment by KoalaBear84** [comment]
I'm having the exact same problem. If I delete the session.dat OR if I just do ```client.AuthService.SendCodeRequestAsync()``` again it works. When I check ```client.AuthService.IsUserAuthorized()``` and not calling ```SendCodeRequestAsync()``` it does not receive any updates.

Version: 0.3.62

**Comment by KoalaBear84** [comment]
Hmm, I might have found the issue..

Register the event handler BEFORE connecting. I think it should also trigger if you register after the connecting / authentication procedure.

I saw you doing this before connecting in ```GetAutoUpdatesTest()``` in ```TelegramClientTests.cs```

Is this correct? Bug? 'Race' condition like thing?

**Comment by KoalaBear84** [comment]
You should be able to reproduce it with this:
```[Fact]
public virtual async Task GetAutoUpdatesTest()
{
  using (var client = NewClient())
  {
      await client.ConnectService.ConnectAsync();
      var user = await GetUser(client);

      // Register AFTER connecting
      client.UpdatesService.RecieveUpdates += update =>
      {
      };

      await SendMessage(client, user);
      await SendMessage(client, user);
      await SendMessage(client, user);
      await SendMessage(client, user);
    Thread.Sleep(2000);
  }
}

**Comment by vik-borisov** [comment]
> Register the event handler BEFORE connecting. I think it should also trigger if you register after the connecting / authentication procedure.

I'll check it, thx

**Comment by OleksiyMoroz** [comment]
@vik-borisov 
Can you make setting server ip to build client optional? this will solve this issue

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
I do not understand what you want to do. The client needs the IP address of the server to connect to it. If you do not ask, where should the client connect?

**Comment by vik-borisov** [comment]
@ KoalaBear84
i run this case

``` C#
         [Fact]
         public virtual async Task GetAutoUpdatesTest ()
         {
             using (var client = NewClient ())
             {
                 await client.ConnectService.ConnectAsync ();
                 var user = await GetUser (client);

                 // Register AFTER connecting
                 client.UpdatesService.RecieveUpdates + = update =>
                 {
                 };};

                 await SendMessage (client, user);
                 await SendMessage (client, user);
                 await SendMessage (client, user);
                 await SendMessage (client, user);
                 await Task.Delay (4000);
             }
         }
```

and it's works

**Comment by OleksiyMoroz** [comment]
@vik-borisov 
from sessions created client, not the new?

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
session was old
@KoalaBear84 
However, updates come from the moment the client connects to the server and there is a possibility that part of the updates will be skipped if you subscribe to the message before the connection.
In this case, there are two options:
1) Subscribe to the event before connecting to the server
2) Prompt for updates in the manual mode

**Comment by KoalaBear84** [comment]
Strange that you couldn't reproduce it. I now subscribe to it in the beginning. So for me the issue is solved. Thanks.
