### ISSUE TITLE
help.getConfig and help.getNearestDc

### ISSUE THREAD

**Issue by OleksiyMoroz** [vik-borisov/TelegramClient#44]
Hi!
Can you implement this api's functions? They don't require auth 
![image](https://user-images.githubusercontent.com/20989635/34866353-0096eedc-f785-11e7-968a-43908472bc8b.png)

**Comment by vik-borisov** [comment]
@OleksiyMoroz 
You can write custom implementation of requests to the server:
docs:
https://opentl.github.io/OpenTl.Schema/api/

to send requests you need to use the method SendService.SendRequestAsync (request)

https://github.com/vik-borisov/TelegramClient/blob/5ff6888fb95600b5501abf5d51030604b5aef35b/src/TelegramClient.Core/ApiServies/ConnectApiService.cs#L93

**Comment by OleksiyMoroz** [comment]
@vik-borisov Thank you! Implemented, working, now can handle with phone_migrate errors

**Comment by vik-borisov** [comment]
@OleksiyMoroz errors with the migration of the phone are repeated?

**Comment by OleksiyMoroz** [comment]
@vik-borisov
in cases when I have migrate errors now invalid check sum occurs
solved this by getting nearest dc and create new client each time user login to the app 
So have two attempts to auth now
not the best solution, but works

**Comment by OleksiyMoroz** [comment]
the problem now is:
 1. log in first with the server that given in app settings(this may be wrong and occur error if try auth)
 2. after connect i call getNearestDc and getConfig and that create new client with server from nearest function response
 3. that only do auth
 As you see i make two connection call very fast and this in second may occur flood error to 24 hours
Question: 
 How can I manage with this? How can I connect client in ONE attempt and be sure that server is correct?

**Comment by vik-borisov** [comment]
check it in version 0.4
