### ISSUE TITLE
Chat Photos

### ISSUE THREAD

**Issue by ghost** [vik-borisov/TelegramClient#49]
Hi,

I am currently using your API to get all messages received. However, how do I get the photo uploaded in the "Media" property of the Message or the Update. The Media property doesn't seem to contain any information of the actual bytes for the photo. 

Thanks

**Comment by anna-oake** [comment]
There is a `Sizes` property in your `TPhoto` instance, it contains array of sizes.
You should:
1. Choose the size you want to download
2. Take `LocalId`, `VolumeId`, `Secret` values from the `Location` property of your chosen `TPhotoSize`
3. Instantiate new `TInputFileLocation` object with these values
4. Pass it to the `client.UploadService.GetFile` method
5. The method will return a `TFile` object with `Bytes` property, whooh!

P.S. `GetFile` method will return only 64 Kb chunk of your file, so if the file is bigger than 64 Kb, you have to download all chunks and glue them, the second method's parameter `offset` will help you

Example:
```
private static async Task<byte[]> DownloadBigPhoto(IFileLocation size, ITelegramClient client) {
	var photoBytes = new List<byte>();
	var offset = 0;
	while (true) {
		var file = (await client.UploadService.GetFile(new TInputFileLocation {
			LocalId = size.LocalId,
			VolumeId = size.VolumeId,
			Secret = size.Secret
		}, offset)).As<TFile>();
		photoBytes.AddRange(file.Bytes);
		if (file.Bytes.Length < 65536) {
			return photoBytes.ToArray();
		}
		offset += file.Bytes.Length;
	}
}
```
_Please note that I don't know how to glue chunks nicely and my `List<byte>` way may be wrong and inefficient 🤷‍♀️_

**Comment by vik-borisov** [comment]
This can be transferred to the library

**Comment by anna-oake** [comment]
Yep, that would be nice, I'm always for hiding such thing _inside_ the lib, but please note that my implementation with List<byte> is stupid, I think we should go with smth like streams (?)

**Comment by ghost** [comment]
Thanks @vik-borisov and @aprosvetova
