### ISSUE TITLE
Stops receiving updates

### ISSUE THREAD

**Issue by KoalaBear84** [vik-borisov/TelegramClient#53]
Just to make it official, an issue on it.

The Telegram Client stops receiving updates after some time. I do not really see a pattern. I also do not more logging or debug information about it because there is no ConnectionStateChanged event or something like that. So maybe the underlying connection is killed / stopped.

Example:
```
2018-01-25 13:08:47.1988  [1]  INFO Program.Main Started
*** Program processed all updates
2018-01-26 01:48:30.3146 [28]  INFO Program.ProcessMessage
```

And then after the last line it didn't receive any updates anymore. I tried to reconnect, but that currently also gives an error (will make a ticket about that too). Also manually getting updates fails too, I tried that as a fallback.

**Comment by vik-borisov** [comment]
@KoalaBear84 
need code to reproduce the error.
in my tests - everything works

**Comment by KoalaBear84** [comment]
Yes, the problem is that it mostly works reliable for a couple of hours and then the problem arises. That is something I and Аня (@aprosvetova) can 'reproduce'.

I don't know if there is a possibility to make it run with more debug information, or an event for connection state, if possible.

**Comment by vik-borisov** [comment]
@KoalaBear84 
the library supports tracing via the log4net logger

this is example, which i'm use in tests:
https://github.com/vik-borisov/TelegramClient/blob/684364c58008f0b7c198f47fc051f09e2f7e92d2/tests/TelegramClient.Tests/LogOutputTester.cs#L43

**Comment by KoalaBear84** [comment]
Thanks! I will try to check it out later and run it with full logging, hopefully finding the underlying issue.

**Comment by ghost** [comment]
I also experience this issue after several hours as @KoalaBear84  said.

**Comment by KoalaBear84** [comment]
Hi @danextras 
Thanks for letting us know. I've sent another log to @vik-borisov this morning. Hopefully it will be fixed soon :)

If you have any more info, that would be great!

**Comment by vik-borisov** [comment]
@KoalaBear84 
@danextras 
I found some an information about the updates
![default](https://user-images.githubusercontent.com/4207463/36102297-7fb7185a-103e-11e8-9c4d-2d3cb2d6ccf4.png)

Now we need to make sure that the process is not interrupted

**Comment by ghost** [comment]
Thanks @vik-borisov. If your framework can detect the error and raise an event (or better yet reconnect itself), I think that would be ideal so that it can continue receiving messages for weeks if not months!

**Comment by vik-borisov** [comment]
fixed

**Comment by KoalaBear84** [comment]
@danextras Could you try version 85? It looks like it is fixed now. Running for 16 hours straight now without any problems, still receiving updates!

**Comment by ghost** [comment]
I have mine running on a cloud server and 16 hours wouldn't be unusual for
me but you still end up getting the same error after a while.

**Comment by KoalaBear84** [comment]
Try it with 85. I never reached more than 6 hours or so here, and now its running for 17 hours.
