### ISSUE TITLE
Authorization Problem

### ISSUE THREAD

**Issue by sofiienko** [vik-borisov/TelegramClient#60]
Hello. Thanks for you big work.

I have code like this:

` var client = ClientFactory.BuildClient(new FactorySettings { Id = ApiId, Hash = ApiHash, ServerAddress = ServerAddress, ServerPort = ServerPort });

await client.Result.ConnectService.ConnectAsync();`

 but it doesn`t work.  I have exception 
> Message	"One or more errors occurred. (One or more errors occurred. (Value cannot be null.\r\nParameter name: instance))"	 string

When I change package version to  3,   then  work good

**Comment by vik-borisov** [comment]
@antonsofienko Hi,
Check ApiId, ApiHash, ServerAddress, and ServerPort. They don't be null

**Comment by sofiienko** [comment]
They don`t null.  I just checked

**Comment by sofiienko** [comment]
in  string container.Register(Component.For<ISessionStoreProvider>().Instance(factorySettings.StoreProvider))  in the  method  FillSettings of  class  ClientFactory  field StorePrivider is empty 

 
![default](https://user-images.githubusercontent.com/25910216/36339431-36a2ebce-13ce-11e8-852e-c657164343fa.png)

**Comment by sofiienko** [comment]
All right, I found a problem. I missed StoreProvider field when I created new FactorySettings. 

`
            var client = ClientFactory.BuildClient(new FactorySettings
            { Id = ApiId,
                Hash = ApiHash,
                ServerAddress = _ServerAddress,
                ServerPort = _ServerPort,
                StoreProvider = new TelegramClient.Core.Sessions.FileSessionStoreProvider("session")//this part was null
            });`

I think,  you should update  wiki page

**Comment by vik-borisov** [comment]
@antonsofienko fixed. thx
