### ISSUE TITLE
How to save and repair session

### ISSUE THREAD

**Issue by sofiienko** [vik-borisov/TelegramClient#61]
I have one more question :) I can`t understand how to save and repair session.   I must input verify code always, or there is some serialization functionality available?How use it? Thanks

**Comment by vik-borisov** [comment]
``` C# 
var client = ClientFactory.BuildClient(new FactorySettings { Id = ApiId, Hash = ApiHash, ServerAddress = _ServerAddress, ServerPort = _ServerPort, StoreProvider = new TelegramClient.Core.Sessions.FileSessionStoreProvider("session")});
```
FileSessionStoreProvider save session in the current directory.

**Comment by sofiienko** [comment]
yes, and how I can restore session?

**Comment by vik-borisov** [comment]
The library save and restore session automatically

**Comment by sofiienko** [comment]
How can I get user object?  Task<TUser> MakeAuthAsync  receive string code parameter

**Comment by vik-borisov** [comment]
please, use new library 
https://github.com/OpenTl/OpenTl.ClientApi
